import Image from 'next/image'
import Link from 'next/link'

const questions = [['Personalization','Which family-provided memories invite comfortable, meaningful conversation?'],['Safety','How reliably do caregiver restrictions and distress-aware redirection support a comfortable experience?'],['Family connection','Do preserved stories help families arrive at visits with more ways to connect?'],['Accessible interaction','What pacing, voice, and visual choices work well for different people?']]

export default function Research() {
  return <main>
    <section className="mx-auto grid max-w-7xl items-center gap-14 px-6 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><p className="text-sm font-semibold uppercase tracking-[.22em] text-primary-dark">Learning in the open</p><h1 className="mt-5 text-5xl leading-[1.04] tracking-[-.03em] md:text-7xl">What makes a moment feel meaningful?</h1><p className="mt-7 max-w-2xl text-xl leading-relaxed text-text/70">Mori is exploring how familiar context, patient pacing, and personal choice can support comfortable reminiscence and family connection.</p></div><div className="relative h-[520px]"><div className="absolute inset-4 overflow-hidden rounded-[48%_48%_2rem_2rem] bg-white p-3 shadow-[0_24px_60px_rgba(61,53,40,.16)]"><div className="relative h-full overflow-hidden rounded-[48%_48%_1.4rem_1.4rem]"><Image src="/images/editorial/calm-portrait.webp" alt="Portrait of an older woman at home" fill priority sizes="(max-width: 1024px) 90vw, 520px" className="object-cover" /></div></div><div className="absolute bottom-0 left-0 rounded-2xl bg-[#303b34] px-6 py-4 text-white shadow-xl"><p className="text-sm uppercase tracking-[.16em] text-white/55">The starting point</p><p className="mt-1 text-xl">Listen to the person.</p></div></div></section>
    <section className="border-y border-primary/10 bg-[#e8ded1] py-24"><div className="mx-auto max-w-7xl px-6"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-primary-dark">Questions we want to explore</p><h2 className="mt-4 text-4xl leading-tight">Measure the experience without reducing a person to a metric.</h2></div><div className="grid gap-5 sm:grid-cols-2">{questions.map(([title,text],i)=><article key={title} className="rounded-3xl bg-white/80 p-7"><span className="text-sm text-primary-dark">0{i+1}</span><h3 className="mt-7 text-2xl">{title}</h3><p className="mt-4 leading-relaxed text-text/65">{text}</p></article>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-8 lg:grid-cols-3"><article className="rounded-[2rem] bg-primary-dark p-8 text-white lg:col-span-2"><p className="text-sm uppercase tracking-[.2em] text-white/55">What Mori does not claim</p><h2 className="mt-5 max-w-2xl text-4xl leading-tight">Connection is the purpose. Clinical efficacy has not been established.</h2><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/70">Mori does not diagnose, treat, or slow dementia. Interaction observations guide personalization and are not cognitive assessments.</p></article><article className="rounded-[2rem] border border-text/10 bg-white p-8"><p className="text-sm uppercase tracking-[.2em] text-primary-dark">Research with care</p><h2 className="mt-5 text-3xl">Separate and optional</h2><p className="mt-5 leading-relaxed text-text/65">Any research needs its own consent, study design, appropriate oversight, and review. Ordinary family use does not imply research participation.</p></article></div><div className="mt-12 text-center"><p className="text-lg text-text/65">Interested in future pilot or advisory opportunities?</p><Link href="/#waitlist" className="mt-5 inline-flex rounded-full bg-primary-dark px-7 py-3.5 text-lg text-white">Join the waitlist</Link></div></section>
  </main>
}
